---
title: "2.2.1 Continuous Uniform Distribution"
output:
  pdf_document: default
  html_document: default
---

Suppose X is uniformly distributed on (0, 100).

```{r echo=FALSE}

## We will create a function for generating uniform density plots

## There is a lot happening with the code below, but don't worry, 
## you will NOT be asked to replicate this user-generated function 
## in any assessments, this is simply just set up to generate plots 
## specific to this script.

plotUnif <- function (min, max, type = "b", col = "black") 
{
  if (!is.numeric(min) | !is.vector(min) | any(!is.finite(min))) {
    stop("The minimun of the uniform distribution, 'min', must be a single number")
  }
  if (length(min) != 1) {
    stop("The minimun of the uniform distribution, 'min', must be a single number")
  }
  if (!is.numeric(max) | !is.vector(max) | any(!is.finite(max))) {
    stop("The maximun of the uniform distribution, 'max', must be a single number")
  }
  if (length(max) != 1) {
    stop("The maximun of the uniform distribution, 'max', must be a single number")
  }
  if ((max - min) <= 0) 
    stop("The parameters min and max represent the minimum and maximum values of the uniform distribution, respectively")
  if (!type %in% c("b", "dis", "den", "q")) 
    stop("The argument 'type' must be 'b', 'dis', 'den' or 'q'")
  if (length(col) != 1) 
    stop("The argument 'col' must be a single colour")
  if (col %in% c(NA, NaN, Inf, -Inf)) 
    stop("The argument 'col' must be a single colour")
  oldpar <- par(no.readonly = TRUE)
  on.exit(par(oldpar))
  dom = (max - min)/10
  x = seq(min - dom, max + dom, by = 0.001)
  fx = dunif(x, min = min, max = max)
  Fx = punif(x, min = min, max = max)
  Finvx = qunif(seq(0, 1, by = 0.01), min = min, max = max)
  if (type == "b") {
    par(mfrow = c(1, 3))
    plot(x, fx, type = "l", main = "Density Function", ylab = "f(x)", 
         lwd = 2, col = col)
    segments(min, 0, min, 1/(max - min), lty = 2, col = "white", 
             lwd = 3)
    segments(max, 0, max, 1/(max - min), lty = 2, col = "white", 
             lwd = 3)
    plot(x, Fx, type = "l", main = "Distribution Function", 
         ylab = "F(x)", lwd = 2, col = col)
    abline(h = c(0, 1), lty = 2, col = "gray")
    plot(seq(0, 1, by = 0.01), Finvx, type = "l", xlab = expression(tau), 
         ylab = "", main = "Quantile Function", lwd = 2, 
         col = col)
    title(ylab = expression(paste("F"^"-1", (tau), sep = "")), 
          line = 2.5, cex.lab = 1)
  }
  else if (type == "dis") {
    plot(x, Fx, type = "l", main = "Distribution Function", 
         ylab = "f(x)", lwd = 2, col = col)
    abline(h = c(0, 1), lty = 2, col = "gray")
  }
  else if (type == "den") {
    plot(x, fx, type = "l", main = "Density Function", ylab = "f(x)", 
         lwd = 2, col = col)
    segments(min, 0, min, 1/(max - min), lty = 2, col = "white", 
             lwd = 3)
    segments(max, 0, max, 1/(max - min), lty = 2, col = "white", 
             lwd = 3)
  }
  else if (type == "q") {
    plot(seq(0, 1, by = 0.01), Finvx, type = "l", xlab = expression(tau), 
         ylab = "", main = "Quantile Function", lwd = 2, 
         col = col)
    title(ylab = expression(paste("F"^"-1", (tau), sep = "")), 
          line = 2.5, cex.lab = 1)
  }
}
```

## Find the density, f(x) at x values of 0, 20, 40, 60, 80, 100

```{r}
a <- 0 
b <- 100 
step <- 20 

# Create a sequence starting at 'a', ending on 'b' skipping by 'step'
x <- seq(a, b, by = step) 
x
```

## Calculate the density for sequence 'x'

```{r}
dunif(x, min = a, max = b) 
```

\newpage
## Plot the density of X

```{r}
plotUnif(min = a, max = b, type = "den", col = "red")
```

## Calculate P(20 <= X <= 90) 

```{r}
x1 <- 20 
x2 <- 90

# Rewrite P(x1 <= X <= x2) as P(X <= x2) - P(X <= x1)  
# Note that '<=' and '<' return the same result when the variable is continuous 
prob_x2 <- punif(x2, min = a, max = b)
prob_x1 <- punif(x1, min = a, max = b)

ans <- prob_x2 - prob_x1 
ans
```

## Calculate the 25th percentile

```{r}
percentile <- qunif(0.25, min = 0, max = 100, lower.tail = TRUE)
percentile
```