---
title: "4.4.3 Two proportions test - Test yourself (solution) "
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

## Example two-sample test for equality of proportions 

```{r}
res <- prop.test(x = c(136, 110), n = c(250, 250),  
                 alternative = "two.sided", conf.level = 0.95, 
                 correct = FALSE)# ignore Yates continuity correction 

res 
```


```{r}
res$statistic # this is chi-square statistic with 1 df which happens to be Z-value squared 
res$p.value # two-sided test p_value  
res$estimate # estimates of prop 1, prop 2 
res$conf.int # gives lower and upper confidence limits for the difference, p1 - p2 
```

\newpage

Another approach is to use formula for Z to find z-score, then calculate p-value.

```{r}
x1 <- 136 
x2 <- 110 

n1 <- 250 
n2 <- 250  

p1_hat <- x1/n1 
p2_hat <- x2/n2 

p1_hat_minus_p2_hat <- p1_hat - p2_hat 

p_hat <- (x1 + x2)/(n1 + n2) 

SE_p_hat <-sqrt(p_hat*(1- p_hat)*(1/n1 + 1/n2)) 

z <- p1_hat_minus_p2_hat / SE_p_hat 
cat(round(z, 3))
```

```{r}
p_value <-2*(1-pnorm(z))
cat(round(p_value, 3))
```